Feature: Testing Statement-Processor REST API
    Users should be able to POST batch of transactions to Statement-Processor web service for validation

    Scenario Outline: Post set of transactions for validation
        When user uploads set of transaction records allTransactions <allTransactions> transactionsList <transactionsList>
        Then the server should validate and send back response <response> httpStatusCode <httpStatusCode>

        Examples:
                | allTransactions                                    | transactionsList                                                                                                                                                                                                                                                                                                                | response                                                                                                                                                                          | httpStatusCode |
                | Successful                                         | [{"transactionReference": "3","accountNumber": "NL33ABNA3333333333","startBalance": "300.00","mutation": "+600.00","Description": "AAA","endBalance": "900.00"},{"transactionReference": "4","accountNumber": "NL33ABNA3333333333","startBalance": "200.00","mutation": "+400.00","Description": "AAA","endBalance": "600.00"}] | {"result":"SUCCESSFUL","errorRecords":[]}                                                                                                                                         | 200            |
                | Duplicate_Reference                                | [{"transactionReference": "3","accountNumber": "NL66ABNA6666666666","startBalance": "400.00","mutation": "-100.00","Description": "AAA","endBalance": "300.00"},{"transactionReference": "3","accountNumber": "NL66ABNA6666666666","startBalance": "200.00","mutation": "+400.00","Description": "AAA","endBalance": "600.00"}] | {"result":"DUPLICATE_REFERENCE","errorRecords":[{"reference":3,"accountNumber":"NL66ABNA6666666666"}]}                                                                            | 200            |
                | Incorrect_End_Balance                              | [{"transactionReference": "3","accountNumber": "NL99ABNA9999999999","startBalance": "300.00","mutation": "-100.00","Description": "AAA","endBalance": "300.00"},{"transactionReference": "4","accountNumber": "NL99ABNA9999999999","startBalance": "200.00","mutation": "+400.00","Description": "AAA","endBalance": "600.00"}] | {"result":"INCORRECT_END_BALANCE","errorRecords":[{"reference":3,"accountNumber":"NL99ABNA9999999999"}]}                                                                          | 200            |
                | Duplicate_Reference_Incorrect_End_Balance          | [{"transactionReference": "3","accountNumber": "NL33ABNA1212121212","startBalance": "300.00","mutation": "+600.00","Description": "AAA","endBalance": "800.00"},{"transactionReference": "3","accountNumber": "NL12ABNA1212121212","startBalance": "200.00","mutation": "+400.00","Description": "AAA","endBalance": "600.00"}] | {"result":"DUPLICATE_REFERENCE_INCORRECT_END_BALANCE","errorRecords":[{"reference":3,"accountNumber":"NL12ABNA1212121212"},{"reference":3,"accountNumber":"NL33ABNA1212121212"}]} | 200            |
                | Internal_Server_Error                              | [{"transactionReference": "3","accountNumber": "NL15ABNA1515151515","startBalance": "300.00","mutation": "+600.00","Description": "AAA","endBalance": "900.00"},{"transactionReference": "4","accountNumber": "NL15ABNA1515151515","startBalance": "200.00","mutation": "+400.00","Description": "AAA"}]                        | {"result":"INTERNAL_SERVER_ERROR","errorRecords":[]}                                                                                                                              | 500            |
                | Bad_Request                                        | [{"transactionReference": "3","accountNumber": "NL18ABNA1818181818","startBalance": "300.00","mutation": "+600.00","Description": "AAA","endBalance": "800.00"},{"transactionReference": "3","accountNumber": "NL18ABNA1818181818","startBalance": "200.00","mutation": "=400.00","Description": "AAA","endBalance": "600.00"}] | {"result":"BAD_REQUEST","errorRecords":[]}                                                                                                                                        | 400            |

